defmodule HL7v2.Segment.IN2 do
  @moduledoc """
  Insurance Additional Information (IN2) segment — HL7v2 v2.5.1.

  Contains extended insurance coverage details beyond the IN1 segment.
  72 fields per HL7 v2.5.1 specification. First 30 fields are typed,
  fields 31-72 are preserved as :raw for lossless round-trip.
  """

  use HL7v2.Segment,
    id: "IN2",
    fields: [
      {1, :insured_employee_id, HL7v2.Type.CX, :o, :unbounded},
      {2, :insured_social_security_number, HL7v2.Type.ST, :o, 1},
      {3, :insured_employer_name_and_id, HL7v2.Type.XCN, :o, :unbounded},
      {4, :employer_information_data, HL7v2.Type.IS, :o, 1},
      {5, :mail_claim_party, HL7v2.Type.IS, :o, :unbounded},
      {6, :medicare_health_ins_card_number, HL7v2.Type.ST, :o, 1},
      {7, :medicaid_case_name, HL7v2.Type.XPN, :o, :unbounded},
      {8, :medicaid_case_number, HL7v2.Type.ST, :o, 1},
      {9, :military_sponsor_name, HL7v2.Type.XPN, :o, :unbounded},
      {10, :military_id_number, HL7v2.Type.ST, :o, 1},
      {11, :dependent_of_military_recipient, HL7v2.Type.CE, :o, 1},
      {12, :military_organization, HL7v2.Type.ST, :o, 1},
      {13, :military_station, HL7v2.Type.ST, :o, 1},
      {14, :military_service, HL7v2.Type.IS, :o, 1},
      {15, :military_rank_grade, HL7v2.Type.IS, :o, 1},
      {16, :military_status, HL7v2.Type.IS, :o, 1},
      {17, :military_retire_date, HL7v2.Type.DT, :o, 1},
      {18, :military_non_avail_cert_on_file, HL7v2.Type.ID, :o, 1},
      {19, :baby_coverage, HL7v2.Type.ID, :o, 1},
      {20, :combine_baby_bill, HL7v2.Type.ID, :o, 1},
      {21, :blood_deductible, HL7v2.Type.ST, :o, 1},
      {22, :special_coverage_approval_name, HL7v2.Type.XPN, :o, :unbounded},
      {23, :special_coverage_approval_title, HL7v2.Type.ST, :o, 1},
      {24, :non_covered_insurance_code, HL7v2.Type.IS, :o, :unbounded},
      {25, :payor_id, HL7v2.Type.CX, :o, :unbounded},
      {26, :payor_subscriber_id, HL7v2.Type.CX, :o, :unbounded},
      {27, :eligibility_source, HL7v2.Type.IS, :o, 1},
      {28, :room_coverage_type_amount, HL7v2.Type.RMC, :o, :unbounded},
      {29, :policy_type_amount, HL7v2.Type.PTA, :o, :unbounded},
      {30, :daily_deductible, HL7v2.Type.DDI, :o, 1},
      {31, :living_dependency, HL7v2.Type.IS, :o, 1},
      {32, :ambulatory_status, HL7v2.Type.IS, :o, :unbounded},
      {33, :citizenship, HL7v2.Type.CE, :o, :unbounded},
      {34, :primary_language, HL7v2.Type.CE, :o, 1},
      {35, :living_arrangement, HL7v2.Type.IS, :o, 1},
      {36, :publicity_code, HL7v2.Type.CE, :o, 1},
      {37, :protection_indicator, HL7v2.Type.ID, :o, 1},
      {38, :student_indicator, HL7v2.Type.IS, :o, 1},
      {39, :religion, HL7v2.Type.CE, :o, 1},
      {40, :mothers_maiden_name, HL7v2.Type.XPN, :o, :unbounded},
      {41, :nationality, HL7v2.Type.CE, :o, 1},
      {42, :ethnic_group, HL7v2.Type.CE, :o, :unbounded},
      {43, :marital_status, HL7v2.Type.CE, :o, :unbounded},
      {44, :insureds_employment_start_date, HL7v2.Type.DT, :o, 1},
      {45, :employment_stop_date, HL7v2.Type.DT, :o, 1},
      {46, :job_title, HL7v2.Type.ST, :o, 1},
      {47, :job_code_class, HL7v2.Type.JCC, :o, 1},
      {48, :job_status, HL7v2.Type.IS, :o, 1},
      {49, :employer_contact_person_name, HL7v2.Type.XPN, :o, :unbounded},
      {50, :employer_contact_person_phone_number, HL7v2.Type.XTN, :o, :unbounded},
      {51, :employer_contact_reason, HL7v2.Type.IS, :o, 1},
      {52, :insureds_contact_persons_name, HL7v2.Type.XPN, :o, :unbounded},
      {53, :insureds_contact_person_phone_number, HL7v2.Type.XTN, :o, :unbounded},
      {54, :insureds_contact_person_reason, HL7v2.Type.IS, :o, :unbounded},
      {55, :relationship_to_the_patient_start_date, HL7v2.Type.DT, :o, 1},
      {56, :relationship_to_the_patient_stop_date, HL7v2.Type.DT, :o, :unbounded},
      {57, :insurance_co_contact_reason, HL7v2.Type.IS, :o, 1},
      {58, :insurance_co_contact_phone_number, HL7v2.Type.XTN, :o, :unbounded},
      {59, :policy_scope, HL7v2.Type.IS, :o, 1},
      {60, :policy_source, HL7v2.Type.IS, :o, 1},
      {61, :patient_member_number, HL7v2.Type.CX, :o, 1},
      {62, :guarantors_relationship_to_insured, HL7v2.Type.CE, :o, 1},
      {63, :insureds_phone_number_home, HL7v2.Type.XTN, :o, :unbounded},
      {64, :insureds_employer_phone_number, HL7v2.Type.XTN, :o, :unbounded},
      {65, :military_handicapped_program, HL7v2.Type.CE, :o, 1},
      {66, :suspend_flag, HL7v2.Type.ID, :o, 1},
      {67, :copay_limit_flag, HL7v2.Type.ID, :o, 1},
      {68, :stoploss_limit_flag, HL7v2.Type.ID, :o, 1},
      {69, :insured_organization_name_and_id, HL7v2.Type.XON, :o, :unbounded},
      {70, :insured_employer_organization_name_and_id, HL7v2.Type.XON, :o, :unbounded},
      {71, :race, HL7v2.Type.CE, :o, :unbounded},
      {72, :cms_patients_relationship_to_insured, HL7v2.Type.CE, :o, 1}
    ]
end
