defmodule HL7v2.Segment.PV1 do
  @moduledoc """
  Patient Visit (PV1) segment — HL7v2 v2.5.1.

  Primary visit/encounter information. 52 fields per HL7 v2.5.1 specification.
  """

  use HL7v2.Segment,
    id: "PV1",
    fields: [
      {1, :set_id, HL7v2.Type.SI, :o, 1},
      {2, :patient_class, HL7v2.Type.IS, :r, 1},
      {3, :assigned_patient_location, HL7v2.Type.PL, :o, 1},
      {4, :admission_type, HL7v2.Type.IS, :o, 1},
      {5, :preadmit_number, HL7v2.Type.CX, :o, 1},
      {6, :prior_patient_location, HL7v2.Type.PL, :o, 1},
      {7, :attending_doctor, HL7v2.Type.XCN, :o, :unbounded},
      {8, :referring_doctor, HL7v2.Type.XCN, :o, :unbounded},
      {9, :consulting_doctor, HL7v2.Type.XCN, :o, :unbounded},
      {10, :hospital_service, HL7v2.Type.IS, :o, 1},
      {11, :temporary_location, HL7v2.Type.PL, :o, 1},
      {12, :preadmit_test_indicator, HL7v2.Type.IS, :o, 1},
      {13, :re_admission_indicator, HL7v2.Type.IS, :o, 1},
      {14, :admit_source, HL7v2.Type.IS, :o, 1},
      {15, :ambulatory_status, HL7v2.Type.IS, :o, :unbounded},
      {16, :vip_indicator, HL7v2.Type.IS, :o, 1},
      {17, :admitting_doctor, HL7v2.Type.XCN, :o, :unbounded},
      {18, :patient_type, HL7v2.Type.IS, :o, 1},
      {19, :visit_number, HL7v2.Type.CX, :o, 1},
      {20, :financial_class, HL7v2.Type.FC, :o, :unbounded},
      {21, :charge_price_indicator, HL7v2.Type.IS, :o, 1},
      {22, :courtesy_code, HL7v2.Type.IS, :o, 1},
      {23, :credit_rating, HL7v2.Type.IS, :o, 1},
      {24, :contract_code, HL7v2.Type.IS, :o, :unbounded},
      {25, :contract_effective_date, HL7v2.Type.DT, :o, :unbounded},
      {26, :contract_amount, HL7v2.Type.NM, :o, :unbounded},
      {27, :contract_period, HL7v2.Type.NM, :o, :unbounded},
      {28, :interest_code, HL7v2.Type.IS, :o, 1},
      {29, :transfer_to_bad_debt_code, HL7v2.Type.IS, :o, 1},
      {30, :transfer_to_bad_debt_date, HL7v2.Type.DT, :o, 1},
      {31, :bad_debt_agency_code, HL7v2.Type.IS, :o, 1},
      {32, :bad_debt_transfer_amount, HL7v2.Type.NM, :o, 1},
      {33, :bad_debt_recovery_amount, HL7v2.Type.NM, :o, 1},
      {34, :delete_account_indicator, HL7v2.Type.IS, :o, 1},
      {35, :delete_account_date, HL7v2.Type.DT, :o, 1},
      {36, :discharge_disposition, HL7v2.Type.IS, :o, 1},
      {37, :discharged_to_location, HL7v2.Type.DLD, :o, 1},
      {38, :diet_type, HL7v2.Type.CE, :o, 1},
      {39, :servicing_facility, HL7v2.Type.IS, :o, 1},
      {40, :bed_status, HL7v2.Type.IS, :b, 1},
      {41, :account_status, HL7v2.Type.IS, :o, 1},
      {42, :pending_location, HL7v2.Type.PL, :o, 1},
      {43, :prior_temporary_location, HL7v2.Type.PL, :o, 1},
      {44, :admit_date_time, HL7v2.Type.TS, :o, 1},
      {45, :discharge_date_time, HL7v2.Type.TS, :o, :unbounded},
      {46, :current_patient_balance, HL7v2.Type.NM, :o, 1},
      {47, :total_charges, HL7v2.Type.NM, :o, 1},
      {48, :total_adjustments, HL7v2.Type.NM, :o, 1},
      {49, :total_payments, HL7v2.Type.NM, :o, 1},
      {50, :alternate_visit_id, HL7v2.Type.CX, :o, 1},
      {51, :visit_indicator, HL7v2.Type.IS, :o, 1},
      {52, :other_healthcare_provider, HL7v2.Type.XCN, :b, :unbounded}
    ]
end
